---
- name: Create dir certs SSL
  file: path=/etc/nginx/ssl state=directory

- name: Verify certificate
  stat: path=/etc/nginx/ssl/{{ app_name }}.crt
  register: result_cert_ssl

- name: Generate certs SSL
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "/etc/nginx/ssl/{{ app_name }}.key" -out "/etc/nginx/ssl/{{ app_name }}.crt" -subj "/C=BR/ST=SC/L=Florianopolis/O=geovanaSouza/OU=IT/CN=nodejs"
  when: result_cert_ssl.stat.exists != true

- name: Include VirtualHost
  template:
    src: virtual_server
    dest: "/etc/nginx/sites-available/{{ app_name }}"
  notify:
    - Reload nginx

- name: Enable VirtualHost
  file: src="/etc/nginx/sites-available/{{ app_name }}" dest="/etc/nginx/sites-enabled/{{ app_name }}" state=link
  notify:
    - Reload nginx
