---
- name: Create group app
  group: name={{ app_group }} state=present

- name: Create app user
  user: name={{ app_user }} group={{ app_group }}

- name: Create dir app
  file:
    path: /opt/{{ app_name }}
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Install app
  git:
    repo: "{{ git_repo }}"
    dest: /opt/{{ app_name }}
    force: yes

- name: Install dependencies defined
  npm: name={{ item }} path=/opt/{{ app_name }}
  when: app_dependencies is defined
  with_items: app_dependencies.split(',')

- name: Install dependencies from package.json
  npm: path=/opt/{{ app_name }}

- name: Start app
  command: pm2 start server.js -i max --name={{ app_name }}
  args:
    chdir: /opt/{{ app_name }}/

