---
- name: Preparing server to get facts server
  hosts: all
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson

- name: Installing nodejs
  hosts: nodejs
  roles:
  - nodejs_install

- name: Installing app
  hosts: nodejs
  roles:
  - { role: deploy_app, app_user: "{{ app1_user }}", app_group: "{{ app1_group }}", app_name: "{{ app1_name }}", app_dependencies: "{{ app1_dependencies }}" }
