---
- name: Preparing server to get facts server
  hosts: all
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson

- name: Installing nodejs
  hosts: nodejs
  roles:
  - nodejs_install

- name: Installing nginx
  hosts: web_front
  roles:
  - nginx_install

- include: deploy_app.yml
