---
- name: Installing app
  hosts: app1
  roles:
  - { role: deploy_app, app_user: "{{ app1_user }}", app_group: "{{ app1_group }}", app_name: "{{ app1_name }}", app_dependencies: "{{ app1_dependencies }}", git_repo: "{{ git1_repo }}" }
